### ISSUE TITLE
Usage instructions do not work

### ISSUE THREAD

**Issue by davidak** [nix-gui/nix-gui#102]
I followed the instructions and got an error:

```
[davidak@gaming:~]$ nix run github:nix-gui/nix-gui nix-gui
error: getting status of '/home/davidak/github:nix-gui/nix-gui': No such file or directory
```

https://github.com/nix-gui/nix-gui/blob/master/docs/usage.org

I think that syntax is flakes and that is still an unreleased feature.

Please clarify the instructions/requirements.

**Comment by lapp0** [comment]
Yes, sorry about that, it should be fixed in the referenced PR.

**Comment by lapp0** [comment]
If these instructions worked, please let me know. I'd also like your general thoughts on the current UX WIP and how it might be improved in a separate issue if you have the time.
