### ISSUE TITLE
nix run github:nix-gui/nix-gui doesn't work from official NixOS.org virtualbox OVA

### ISSUE THREAD

**Issue by ParetoOptimalDev** [nix-gui/nix-gui#147]
After enabling flakes, when this happens:

```sh
[demo@nixos:~]$ nix run github:nix-gui/nix-gui
INFO:Retrieving option values for module "/etc/nixos/configuration.nix"
ERROR:[Errno 2] No such file or directory: '/etc/nixos/<nixpkgs/nixos/modules/installer/virtualbox-demo.nix>'
```

I guess this is because of the config piece that imports that in `/etc/nixos/configuration.nix`:

```nix
# ... snip ...
imports = [ <nixpkgs/nixos/modules/installer/virtualbox-demo.nix> ];
# ... snip ...
```

When I try to run it again, no error is displayed but it's also all blank:

![Screenshot_20211023_044202](https://user-images.githubusercontent.com/93023868/138542740-663f86b0-4127-4d8a-ab76-7a3dc9a19dfc.png)

**Comment by lapp0** [comment]
This appears to be a problem with Nix-Gui working with the breeze theme, closed in favor of https://github.com/nix-gui/nix-gui/issues/174
