### ISSUE TITLE
Pass correct `modulesPath` & ensure it can be used in `imports`

### ISSUE THREAD

**Issue by lapp0** [nix-gui/nix-gui#203]
https://github.com/nix-gui/nix-gui/pull/187#issuecomment-973843397

**Comment by lapp0** [comment]
@milahu actually I think we might want to close this since [`lib.nix`](https://github.com/nix-gui/nix-gui/blob/master/nixui/nix/lib.nix) already uses `NIX_PATH` implicitly, and we can get `modulesPath` from `<nixpkgs/nixos/modules>`.

**Comment by lapp0** [comment]
We also have to solve the `undefined variable` problem

# Background

Additionally, Nix-Gui doesn't do a full evaluation of any options, it just extracts what's necessary for its expression (without any context). We want to ensure the integrity of the bidirectional mapping from python object <--> expression string. I'm sure you've noticed the "Expression" button that all options include. The object form and expression string form are part of `option_definition.OptionDefinition`.

Nix-Gui will extract the contextless expression string and load an `OptionDefinition` with it. So the nix expression (`1+1`) will be represented as the python object `int(2)`. (https://github.com/nix-gui/nix-gui/blob/master/nixui/options/option_definition.py#L289-L294)

This doesn't work with expressions that require contexts from function-module arguments, `let ... in ...`, `with ...`, etc. 

`[ (modulesPath + "/installer/scan/not-detected.nix")];` is one of these expressions that requires context. 

`imports` is evaluated using `OptionDefinition` here https://github.com/nix-gui/nix-gui/blob/master/nixui/options/parser.py#L75-L80 

# Solution 0: Don't use `OptionDefinition` to collect `imports` 

We currently piggyback off of `OptionDefinition` to get the `imports`, however that doesn't work properly when it depends on `modulesPath`. Perhaps we should create a function in `lib.nix` that specifically evaluates imports. It could work as follows:

```
nix-instantiate --eval -E 'builtins.head (import /etc/nixos/hardware-configuration.nix {config = {}; pkgs = import <nixpkgs> {}; lib = {}; modulesPath = <nixpkgs/nixos/modules>;}).imports'
/etc/nixos/nixpkgs/nixos/modules/installer/scan/not-detected.nix
```

# Solution 1: Full context evaluation in `OptionDefinition`

This is something that will need to be done eventually regardless, but is quite a challenge and likely impossible until `rnix-lsp` matures.

If we change `OptionDefinition` to provide all the context made available during actual `nix` evaluation, we will be able to make `imports` work. This may be achievable with https://github.com/nix-community/rnix-lsp once all the changes from https://github.com/aaronjanse/nix-eval-lsp are merged, and a myriad of other forms of evaluation are implemented.

Once this is done, the `expression` `FieldWidget` should not only allow editing ofthe contextless expression string, but also the context surrounding the definition. This may be as "simple" as a list of evaluation dependencies, widgets to change them, and the information about the options which would be impacted if changed.

**Comment by milahu** [comment]
> until `rnix-lsp` matures

agree ... we need both: general-purpose editor (free form) and domain-specific editor (edit nix config per allowed schema)

**Comment by lapp0** [comment]
@milahu any interest in looking into https://github.com/NixOS/nix/issues/5612 since you already are knowledgeable about how `--json` and `--xml` are generated?
