### ISSUE TITLE
fix `error: undefined variable 'modulesPath'`

### ISSUE THREAD

**Issue by lapp0** [nix-gui/nix-gui#204]
Reproduce with `nix run nix-gui -- -n -c nix-gui/nixui/tests/sample/configuration.nix`

Output:
```
INFO:Retrieving option values for module "/home/andrew/p/nix-gui/nixui/tests/sample/configuration.nix"
INFO:Retrieving option values for module "/home/andrew/p/nix-gui/nixui/tests/sample/hardware-configuration.nix"
ERROR:Error evaluating (modulesPath + "/installer/scan/not-detected.nix"):
error=NixEvalError("""
error: undefined variable 'modulesPath'

       at «string»:1:2:

            1| (modulesPath + "/installer/scan/not-detected.nix")
             |  ^

""")
ERROR:failed to load element 0 of 
[ (modulesPath + "/installer/scan/not-detected.nix")
    ]

```

This is probably because it's being evaluated in `OptionDefinition` without the context of the passed arguments. Only `imports` are directly evaluated by `Nix-Gui`, everything else is just syntax for editing.

**Comment by milahu** [comment]
> You can run again with diskcache off (`-n`) to reproduce.

yepp! `error: undefined variable 'modulesPath'`

nix path is ok

```
echo $NIX_PATH | tr : '\n'
nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos
nixos-config=/etc/nixos/configuration.nix
/nix/var/nix/profiles/per-user/root/channels
```

so modulesPath should be `/nix/var/nix/profiles/per-user/root/channels`

**Comment by lapp0** [comment]
I'm not sure we should use `NIX_PATH` directly. See first comment in https://github.com/nix-gui/nix-gui/issues/203

Closed in favor of the aforementioned
