### ISSUE TITLE
dark theme: background is too light when value is selected

### ISSUE THREAD

**Issue by milahu** [nix-gui/nix-gui#208]
when a value is selected (click on string/expression), the background is too bright

continue #187 

same in breeze and kvantum theme

<img src="https://user-images.githubusercontent.com/12958815/142668776-6a4037b1-8460-462a-bc52-30a1dee1bfd3.png" width="855">

**Comment by lapp0** [comment]
That's funny. `QColor.darker` must brighten when using dark mode.

https://github.com/nix-gui/nix-gui/blob/master/nixui/graphics/option_display.py#L221

**Comment by milahu** [comment]
just use `QtGui.QPalette().Highlight`?

**Comment by lapp0** [comment]
Yes, please see #209

**Comment by milahu** [comment]
fixed : )
