### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by boredom101** [nix-gui/nix-gui#249]
I was thinking that it would be useful to have continuous integration so that we can automatically run the tests on pull requests. I'm not sure if we should implement this with GitHub Actions, Hydra, or something else.

**Comment by lapp0** [comment]
I believe this is redundant with https://github.com/nix-gui/nix-gui/issues/68

We definitely need CI. v0.2 will be released shortly, after which v0.3 will tackle up a few high priority issues https://github.com/nix-gui/nix-gui/milestone/2, then the next milestone focuses on build improvements including CI https://github.com/nix-gui/nix-gui/milestone/6

Although if you're interested in CI there is no problem tackling it early.

**Comment by lapp0** [comment]
closing in favor of #68.
