### ISSUE TITLE
Feature Request: Support the Pinephone

### ISSUE THREAD

**Issue by jgarte** [nix-gui/nix-gui#265]
Hi,

Is this app mobile friendly?

I think it would be nice to consider usage on the pinephone/mobile optimization for future developments.

I would definitely prefer to use NixOS on the pinephone "without coding".

Some inspiration:

https://github.com/JasonG-FR/PineBattery

https://mobile.nixos.org/

**Comment by jgarte** [comment]
Oops,

Just read this: https://github.com/nix-gui/nix-gui#serve-mobile-users

**Comment by lapp0** [comment]
Right, but it is still helpful to know that this is a feature people are interested in.

**Comment by jgarte** [comment]
@lapp0 Yes, definitely interested!

I'd like to manage various nix profiles from a GUI.

**Comment by lapp0** [comment]
semi-related, main blocking issue for work on pinephone https://github.com/nix-gui/nix-gui/issues/266
