### ISSUE TITLE
Support Foreign Distros

### ISSUE THREAD

**Issue by jgarte** [nix-gui/nix-gui#268]
Since nix is a universal package manager I think it would be very useful for nix-gui to work not just for NixOS in the same way that Nix works not just for NixOS.

My use case is that I'm using [sxmo](https://sxmo.org) on the pinphone and I have nix available. It works great. I just need a GUI :)

**Comment by boredom101** [comment]
I have set it up on WSL Ubuntu with x11 forwarding for testing, so it's possible. Though right now, nix-gui could only modify NixOS configurations, and can not do package management. But if it is still useful I could write up a guide.

**Comment by jgarte** [comment]
Sure, A guide would be useful for sure. Thank  you

**Comment by lapp0** [comment]
Nix-Gui is first and foremost a tool to set NixOS options. Once we have a proper [package manager](https://github.com/nix-gui/nix-gui/issues/85) in place, perhaps that could be used for non-nix distros. However that would be just a small part of Nix-Gui. 

Perhaps a better option for your use case specifically is for smxo to be made available on NixOS and the `nix-gui --mobile` GUI to be built out.
